#
# Manifest for module 'CoreTools'
#
# Generated by: Luc Dekens
#
# Generated on: 19-12-16
#

@{
  RootModule        = 'CoreTools'
  ModuleVersion     = '1.0'
  GUID              = 'd42ab4b0-405a-4edc-8718-a5ed7e98ce3a'
  Author            = 'Luc Dekens'
  CompanyName       = 'Unknown'
  Copyright         = '(c) 2016 Luc Dekens. All rights reserved.'
  PowerShellVersion = '6.0'
  FunctionsToExport = 'Get-CorePlatform','New-CoreScheduledTask'
}
